#!/usr/bin/env bash
#
# build-android
#
# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

set -e

SWIFT_PATH="$( cd "$(dirname $0)/.." && pwd )" 

ANDROID_NDK_PATH="${ANDROID_NDK_PATH:?Please set the Android NDK path in the ANDROID_NDK_PATH environment variable}"
ANDROID_ICU_PATH=${SWIFT_PATH}/libiconv-libicu-android

SWIFT_ANDROID_TOOLCHAIN_PATH="${SWIFT_PATH}/swift-android-toolchain"
SWIFT_ANDROID_BUILD_PATH="${SWIFT_PATH}/build/Ninja-ReleaseAssert"

cd ${SWIFT_PATH}/swift-corelibs-libdispatch

mkdir -p $SWIFT_ANDROID_BUILD_PATH/libdispatch-android-linux-armv7

mkdir -p .build
cd .build

ANDROID_STANDALONE_TOOLCHAIN=`realpath ./android-standalone-toolchain`
ANDROID_STANDALONE_SYSROOT=$ANDROID_STANDALONE_TOOLCHAIN/sysroot

if [ ! -d android-standalone-toolchain ]; then
    echo Creating Android standalone toolchain ...
    $ANDROID_NDK_PATH/build/tools/make_standalone_toolchain.py --api 21 --arch arm --stl libc++ --install-dir $ANDROID_STANDALONE_TOOLCHAIN --force -v
fi

export PATH=$ANDROID_STANDALONE_TOOLCHAIN/bin:$PATH
export CC=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-clang
export CXX=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-clang++
export AR=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-ar
export AS=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-as
export LD=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-ld
export RANLIB=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-ranlib
export NM=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-nm
export STRIP=$ANDROID_STANDALONE_TOOLCHAIN/bin/arm-linux-androideabi-strip
export CHOST=arm-linux-androideabi
export ARCH_FLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16"
export ARCH_LINK="-march=armv7-a -Wl,--fix-cortex-a8"
export CPPFLAGS=" ${ARCH_FLAGS} -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing "
export CXXFLAGS=" ${ARCH_FLAGS} -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -frtti -fexceptions -std=c++11 -Wno-error=unused-command-line-argument "
export CFLAGS=" ${ARCH_FLAGS} -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing "
export LDFLAGS=" ${ARCH_LINK} "

if [ ! -f libdispatch.so ]; then
    pushd $ANDROID_STANDALONE_SYSROOT
        pushd $SWIFT_PATH
            pushd $SWIFT_ANDROID_BUILD_PATH/libdispatch-android-linux-armv7
                # Libfoundation script is not completely prepared to handle cross compilation yet.
                # ln -sf $SWIFT_ANDROID_BUILD_PATH/swift-linux-x86_64/lib/swift $ANDROID_STANDALONE_SYSROOT/usr/lib/
                # cp $SWIFT_ANDROID_BUILD_PATH/swift-linux-x86_64/lib/swift/android/armv7/* $SWIFT_ANDROID_BUILD_PATH/swift-linux-x86_64/lib/swift/android/

                # SWIFTCFLAGS="-DDEPLOYMENT_TARGET_ANDROID -DDEPLOYMENT_ENABLE_LIBDISPATCH -I$ANDROID_NDK_PATH/platforms/android-21/arch-arm/usr/include" \
                # LDFLAGS="-fuse-ld=gold --sysroot=$ANDROID_NDK_PATH/platforms/android-21/arch-arm -L$ANDROID_NDK_PATH/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x -L$ANDROID_ICU_PATH/armeabi-v7a -L$ANDROID_STANDALONE_SYSROOT/usr/lib -ldispatch " \

                #cmake .

                cmake \
                    -G Ninja \
                    -DINSTALL_LIBDIR="$SWIFT_ANDROID_TOOLCHAIN_PATH/usr/lib" \
                    -DCMAKE_SWIFT_COMPILER="$SWIFT_ANDROID_TOOLCHAIN_PATH/usr/bin/swiftc" \
                    -DCMAKE_C_COMPILER="$CC" \
                    -DCMAKE_C_COMPILER_TARGET="armv7-none-linux-androideabi" \
                    -DCMAKE_CXX_COMPILER="$CXX" \
                    -DCMAKE_C_FLAGS="-Wno-error=unknown-attributes -Wno-error=unused-function -DDEPLOYMENT_TARGET_ANDROID -DDEPLOYMENT_ENABLE_LIBDISPATCH --sysroot=$ANDROID_NDK_PATH/platforms/android-21/arch-arm -I$ANDROID_ICU_PATH/armeabi-v7a/include -I${SDKROOT}/lib/swift -I$ANDROID_STANDALONE_SYSROOT/usr/include" \
                    -DCMAKE_SWIFT_FLAGS="-I$ANDROID_STANDALONE_SYSROOT/usr/include" \
                    -DCMAKE_SYSTEM_NAME=Android \
                    -DCMAKE_SYSTEM_PROCESSOR=armv7l \
                    -DENABLE_SWIFT=1 \
                    -DENABLE_TESTING=0 \
                    -DDISPATCH_ENABLE_ASSERTS=1 \
                    -DCMAKE_REQUIRED_INCLUDES="$ANDROID_ICU_PATH/armeabi-v7a/include ${SDKROOT}/lib/swift $ANDROID_STANDALONE_SYSROOT/usr/include" \
                    $SWIFT_PATH/swift-corelibs-libdispatch

                cp -r /usr/include/uuid $ANDROID_STANDALONE_SYSROOT/usr/include 
                sed -i~ "s/-I.\/ -I\/usr\/include\/x86_64-linux-gnu  -I\/usr\/include\/x86_64-linux-gnu    -I\/usr\/include\/libxml2//" build.ninja
                sed -i~ "s/-licui18n/-licui18nswift/g" build.ninja
                sed -i~ "s/-licuuc/-licuucswift/g" build.ninja
                sed -i~ "s/-licudata/-licudataswift/g" build.ninja

                ninja && ninja install

            popd
        popd
    popd
fi

